version: '3.8'

services:
  brt-app:
    build: .
    container_name: brt-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
